"""
Standardized machine-readable validation flags for Module 2: Document Validation.
"""
from enum import Enum


class ValidationFlag(str, Enum):
    # --- Input & Mandatory Field Flags ---
    MISSING_DOCUMENT_NUMBER = "MISSING_DOCUMENT_NUMBER"
    MISSING_NAME = "MISSING_NAME"
    MISSING_DATE_OF_BIRTH = "MISSING_DATE_OF_BIRTH"
    MISSING_EXPIRY_DATE = "MISSING_EXPIRY_DATE"
    MISSING_NATIONALITY = "MISSING_NATIONALITY"
    MISSING_DOCUMENT_TYPE = "MISSING_DOCUMENT_TYPE"
    INVALID_FIELD_TYPE = "INVALID_FIELD_TYPE"
    INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT"
    INCOMPLETE_DATA = "INCOMPLETE_DATA"

    # --- Document Number & Format Flags ---
    INVALID_DOCUMENT_NUMBER_FORMAT = "INVALID_DOCUMENT_NUMBER_FORMAT"
    INVALID_DOCUMENT_NUMBER_LENGTH = "INVALID_DOCUMENT_NUMBER_LENGTH"
    INVALID_DOCUMENT_NUMBER_CHARACTERS = "INVALID_DOCUMENT_NUMBER_CHARACTERS"
    COUNTRY_FORMAT_MISMATCH = "COUNTRY_FORMAT_MISMATCH"
    SUSPICIOUS_PLACEHOLDER_NUMBER = "SUSPICIOUS_PLACEHOLDER_NUMBER"
    UNRECOGNIZED_DOCUMENT_TYPE = "UNRECOGNIZED_DOCUMENT_TYPE"

    # --- Date Logic Flags ---
    INVALID_DATE_OF_BIRTH = "INVALID_DATE_OF_BIRTH"
    FUTURE_DATE_OF_BIRTH = "FUTURE_DATE_OF_BIRTH"
    UNREALISTIC_AGE = "UNREALISTIC_AGE"
    FUTURE_ISSUE_DATE = "FUTURE_ISSUE_DATE"
    INVALID_DATE_LOGIC = "INVALID_DATE_LOGIC"
    EXPIRY_BEFORE_ISSUE = "EXPIRY_BEFORE_ISSUE"
    EXPIRED_DOCUMENT = "EXPIRED_DOCUMENT"
    EXPIRING_SOON = "EXPIRING_SOON"
    EXPIRY_UNKNOWN = "EXPIRY_UNKNOWN"
    INVALID_VISA_VALIDITY = "INVALID_VISA_VALIDITY"
    INVALID_STAY_DURATION = "INVALID_STAY_DURATION"

    # --- MRZ Validation Flags ---
    MRZ_STRUCTURE_INVALID = "MRZ_STRUCTURE_INVALID"
    MRZ_CHECKSUM_INVALID = "MRZ_CHECKSUM_INVALID"
    MRZ_DOCUMENT_NUMBER_MISMATCH = "MRZ_DOCUMENT_NUMBER_MISMATCH"
    MRZ_DATE_OF_BIRTH_MISMATCH = "MRZ_DATE_OF_BIRTH_MISMATCH"
    MRZ_EXPIRY_DATE_MISMATCH = "MRZ_EXPIRY_DATE_MISMATCH"
    MRZ_COMPOSITE_CHECKSUM_INVALID = "MRZ_COMPOSITE_CHECKSUM_INVALID"
    MRZ_UNAVAILABLE = "MRZ_UNAVAILABLE"
    LOW_MRZ_CONFIDENCE = "LOW_MRZ_CONFIDENCE"
    LOW_OCR_CONFIDENCE = "LOW_OCR_CONFIDENCE"

    # --- Blacklist & Watchlist Flags ---
    DOCUMENT_ON_BLACKLIST = "DOCUMENT_ON_BLACKLIST"
    IDENTITY_ON_WATCHLIST = "IDENTITY_ON_WATCHLIST"
    BLACKLIST_MATCH = "BLACKLIST_MATCH"
    WATCHLIST_DATABASE_UNAVAILABLE = "WATCHLIST_DATABASE_UNAVAILABLE"
    WATCHLIST_LOOKUP_INCONCLUSIVE = "WATCHLIST_LOOKUP_INCONCLUSIVE"
    CLEAN_RECORD_CONFIRMED = "CLEAN_RECORD_CONFIRMED"

    # --- Duplicate Identity Flags ---
    DUPLICATE_IDENTITY_FOUND = "DUPLICATE_IDENTITY_FOUND"
    MULTIPLE_DOCUMENT_NUMBERS = "MULTIPLE_DOCUMENT_NUMBERS"
    POSSIBLE_IDENTITY_COLLISION = "POSSIBLE_IDENTITY_COLLISION"
    DUPLICATE_LOOKUP_INCONCLUSIVE = "DUPLICATE_LOOKUP_INCONCLUSIVE"

    # --- Standards Compliance Flags ---
    STANDARDS_COMPLIANT = "STANDARDS_COMPLIANT"
    STANDARDS_NON_COMPLIANT = "STANDARDS_NON_COMPLIANT"
    UNSUPPORTED_STANDARD = "UNSUPPORTED_STANDARD"
    LOW_CONFIDENCE_STANDARD = "LOW_CONFIDENCE_STANDARD"
    STANDARDS_CHECK_INCOMPLETE = "STANDARDS_CHECK_INCOMPLETE"
